#!/usr/bin/env python3
"""Builds caps.dat and provider_data.h from providers.toml.

caps.dat mirrors the legacy CrownMPQ.exe output byte for byte:
    u32  size         bytes after this field: id + name\\0 + description\\0 + caps
    u32  id           provider id stored little-endian (the text 'CNLK' reversed on disk)
    char name         null-terminated provider name
    char description  null-terminated description
    Caps caps         9 x u32 storm ABI struct, see storm/util/snet.hpp
"""

import argparse
import hashlib
import sys
import tomllib
import re
import struct
from pathlib import Path

# Frozen storm ABI values from storm_sdk's <storm/util/snet.hpp>.
# static_assert(sizeof(Caps) == CAPS_SIZE_BYTES) in SNP/SNPModule.h guards the C++ side
CAPS_SIZE_BYTES = 36
CAPS_FLAGS = 0x3  # CapsFlags::PageLockedBuffers | CapsFlags::BasicInterface
CAPS_MAX_QUEUE_SIZE = 16
CAPS_MAX_PLAYERS = 256
CAPS_BYTES_PER_SECOND = 100000
CAPS_LATENCY = 50
CAPS_TURNS_IN_TRANSIT = 2

VALID_TURNS_PER_SECOND = {4, 6, 8, 10, 12}  # mirrors include/TurnsPerSecond.h
MAX_DESCRIPTION_BYTES = 128  # storm copies the description into ProviderInfo::description[128]
DESCRIPTION_LINE_LIMIT = 9  # rows available in the StarCraft description box


def fail(message):
    sys.exit(f"error: {message}")


def read_version_string(version_header):
    text = Path(version_header).read_text(encoding="utf-8")
    match = re.search(r'#define CL_VERSION_STRING "(.*)"', text)
    if not match:
        fail(f"no CL_VERSION_STRING define found in {version_header}")
    return match.group(1)


def load_providers(toml_path):
    with open(toml_path, "rb") as file:
        config = tomllib.load(file)

    providers = config.get("provider")
    if not providers:
        fail(f"{toml_path} declares no [[provider]] entries")

    max_packet_size = config.get("max_packet_size")
    if not isinstance(max_packet_size, int) or not 128 <= max_packet_size <= 512:
        fail("max_packet_size must be an integer between 128 and 512")

    for index, provider in enumerate(providers):
        label = f"provider[{index}]"
        for field in ("id", "name", "subtitle", "turns_per_second"):
            if field not in provider:
                fail(f"{label} is missing '{field}'")
        if len(provider["id"]) != 4 or not provider["id"].isascii():
            fail(f"{label}.id must be 4 ascii characters")
        if provider["turns_per_second"] not in VALID_TURNS_PER_SECOND:
            valid = ", ".join(str(value) for value in sorted(VALID_TURNS_PER_SECOND))
            fail(f"{label}.turns_per_second must be one of: {valid}")
    return config, providers


def provider_id_u32(id_text):
    # Composes like the C multi-char constant 'CNLK'; little-endian storage reverses it on disk
    return int.from_bytes(id_text.encode("ascii"), "big")


def build_description(version_string, subtitle):
    # 0x04 switches the description to green text, 0x01 reverts it
    description = f"Version: {version_string}\n\x04Peer to peer networking using ICE\n\x01{subtitle}\n"
    line_count = len(description.splitlines())
    if line_count > DESCRIPTION_LINE_LIMIT:
        print(f"warning: description is {line_count} lines, the game box shows {DESCRIPTION_LINE_LIMIT}")
    if len(description.encode("latin-1")) > MAX_DESCRIPTION_BYTES:
        print(f"warning: description exceeds {MAX_DESCRIPTION_BYTES} bytes, storm's buffer is that size")
    return description


def build_caps_bytes(max_packet_size, turns_per_second):
    return struct.pack(
        "<9I",
        CAPS_SIZE_BYTES,
        CAPS_FLAGS,
        max_packet_size,
        CAPS_MAX_QUEUE_SIZE,
        CAPS_MAX_PLAYERS,
        CAPS_BYTES_PER_SECOND,
        CAPS_LATENCY,
        turns_per_second,
        CAPS_TURNS_IN_TRANSIT,
    )


def build_caps_dat(providers, version_string, max_packet_size):
    blob = bytearray()
    for provider in providers:
        description = build_description(version_string, provider["subtitle"])
        name_bytes = provider["name"].encode("latin-1")
        description_bytes = description.encode("latin-1")
        caps_bytes = build_caps_bytes(max_packet_size, provider["turns_per_second"])

        size = 4 + len(name_bytes) + 1 + len(description_bytes) + 1 + len(caps_bytes)
        blob += struct.pack("<II", size, provider_id_u32(provider["id"]))
        blob += name_bytes + b"\0"
        blob += description_bytes + b"\0"
        blob += caps_bytes
    return bytes(blob)


def render_provider_data_h(providers, max_packet_size):
    ids = ", ".join(f"0x{provider_id_u32(provider['id']):08X}" for provider in providers)
    return (
        "#pragma once\n"
        "// Generated by scripts/build_caps.py from scripts/providers.toml - do not edit\n"
        "// Requires u32 (storm/types.hpp) to be included first\n"
        "\n"
        "// Largest message the SNP layer accepts; must match caps.dat\n"
        f"inline constexpr u32 MaxPacketSize = {max_packet_size};\n"
        "\n"
        "// Provider ids in caps.dat entry order; order must match what storm enumerates from caps.mpq\n"
        "namespace snp {\n"
        f"inline constexpr u32 provider_ids[] = {{{ids}}};\n"
        "}  // namespace snp\n"
    )


def write_if_changed(path, content_bytes):
    path = Path(path)
    if path.exists() and path.read_bytes() == content_bytes:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content_bytes)


def verify_stamp(toml_path, stamp_path):
    toml_hash = hashlib.sha256(Path(toml_path).read_bytes()).hexdigest()
    stamp_path = Path(stamp_path)
    if not stamp_path.exists():
        fail(f"{stamp_path} is missing; re-run the CMake configure step")
    if toml_hash != stamp_path.read_text(encoding="ascii").strip():
        fail(
            f"{toml_path} changed since CMake was configured. provider_data.h is only\n"
            "regenerated at configure time, so re-run the CMake configure step, then build again"
        )


def compare_with_reference(blob, reference_path):
    reference = Path(reference_path).read_bytes()
    if blob == reference:
        print(f"caps.dat matches reference ({len(blob)} bytes)")
        return
    for offset, (ours, theirs) in enumerate(zip(blob, reference)):
        if ours != theirs:
            break
    else:
        offset = min(len(blob), len(reference))
    print(f"caps.dat differs from reference at offset {offset} (0x{offset:X}):")
    print(f"  reference: {reference[offset:offset + 16].hex(' ')}")
    print(f"  actual:    {blob[offset:offset + 16].hex(' ')}")
    print(f"  lengths: reference {len(reference)}, actual {len(blob)}")
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--providers", required=True, help="path to providers.toml")
    parser.add_argument("--version-header", help="generated crownlink/version.h to read the version string from")
    parser.add_argument("--dat-out", help="caps.dat output path")
    parser.add_argument("--header-out", help="generated/crownlink/provider_data.h output path")
    parser.add_argument("--stamp", help="providers.toml content hash; written normally, read with --verify")
    parser.add_argument("--verify", action="store_true", help="only check providers.toml against the stamp")
    parser.add_argument("--compare", help="compare the built caps.dat against a reference file")
    args = parser.parse_args()

    config, providers = load_providers(args.providers)

    if args.verify:
        if not args.stamp:
            parser.error("--verify requires --stamp")
        verify_stamp(args.providers, args.stamp)
        return

    if not args.version_header:
        parser.error("--version-header is required unless --verify")
    if not args.dat_out and not args.header_out and not args.compare:
        parser.error("nothing to do: pass at least one of --dat-out, --header-out, --compare")

    version_string = read_version_string(args.version_header)
    blob = build_caps_dat(providers, version_string, config["max_packet_size"])

    if args.dat_out:
        write_if_changed(args.dat_out, blob)
    if args.header_out:
        write_if_changed(args.header_out, render_provider_data_h(providers, config["max_packet_size"]).encode())
    if args.stamp:
        write_if_changed(args.stamp, hashlib.sha256(Path(args.providers).read_bytes()).hexdigest().encode("ascii"))
    if args.compare:
        compare_with_reference(blob, args.compare)


if __name__ == "__main__":
    main()